In [ ]:
import tensorflow as tf
import numpy as np

y = np.asarray([20,10,0,-10.,-20.])

y_val = tf.convert_to_tensor(y)

x = np.asarray([20,1,1,-10.,-20.])

l2 = tf.square(y - x)
l2_out = tf.round(l2)

l1 = tf.abs(y - x)

# print(y)
print(l1.numpy())

[ 0. 81.  1.  0.  0.]


In [ ]:
import tensorflow as tf

x = tf.constant([12, 14, 20, 15])
y = tf.Variable(x*3 + 100)
tf.print(y)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([136, 142, 160, 145], dtype=int32)>


In [ ]:
import tensorflow as tf

image = tf.image.decode_png(tf.io.read_file('./pict.png'), channels=3)
tf.print(tf.shape(image))
print('\n')
tf.print(image[10:15,0:4,1])

[1440 2560 3]


[[155 155 155 155]
 [156 156 156 156]
 [157 157 157 156]
 [158 158 157 157]
 [159 159 158 158]]


In [ ]:
#fixed tensor
import tensorflow as tf

a = tf.zeros([2,3])

b = tf.ones([4,3])

c = tf.fill([2,3], 7)

d = tf.constant([2,4,1,5])
tf.print(d)

[2 4 1 5]


In [ ]:
# sequence tensor
import tensorflow as tf

a = tf.range(start=5, limit=50, delta=8)

b = tf.linspace(10.0, 31.0, 5)
tf.print(b)

[10 15.25 20.5 25.75 31]


In [ ]:
# random tensor
import tensorflow as tf

a = tf.random.uniform([2,3], minval=0, maxval=7)

b = tf.random.normal([2,3], mean=3, stddev=5)

tf.print(a)

[[2.78276849 2.36601281 5.46969]
 [0.901890755 -4.2145195 4.04254627]]


In [ ]:
# activation function
import tensorflow as tf

a = tf.nn.tanh([10,5,2,1,0.5,0,-0.5,-1.,-2.,-5.,-10.])

b = tf.sigmoid([10,5,2,1,0.5,0,-0.5,-1.,-2.,-5.,-10.])

c = tf.nn.relu([-5,2,-1,10])

d = tf.nn.relu6([[-5,2,-1,10],[10,-14,4,-5]])

e = tf.nn.elu([10,5,2,1,0.5,0,-0.5,-1.,-2.,-5.,-10.])
print(e.numpy())

[10.          5.          2.          1.          0.5         0.
 -0.39346933 -0.63212055 -0.86466473 -0.99326205 -0.9999546 ]


In [ ]:
# loss function
import tensorflow as tf
import numpy as np

# bayangan prediksi model
pred = np.asarray([0.2,0.3,0.7,10.0,13.0,3.4,5.1,6.5,2.4])
#konversi data ke tensor
x_val = tf.convert_to_tensor(pred)
# bayangan hasil asli
actual = np.asarray([0.1,0.4,0.5,9.0,14.0,3.5,5.0,6.0,2.1])

#L2 loss:L1=(pred-actual)^2
l2 = tf.square(pred-actual)
l2_out = tf.round(l2)

#L2 Loss:L1=abs(pred-actual)
l1 = tf.abs(pred-actual)
l1_out = l1

#cross entropy loss
softmax_xentropy_var = \
   tf.nn.sigmoid_cross_entropy_with_logits(logits=l1_out, labels=l2_out)
print(softmax_xentropy_var.numpy())

[0.74439666 0.74439666 0.79813887 0.31326169 0.31326169 0.74439666
 0.74439666 0.97407698 0.85435524]


In [ ]:
# Optimizers
import tensorflow as tf

# Memasukkan nilai kedalam variable
x = tf.Variable(3.0, dtype=tf.float32)
log_x = tf.math.log(x)
log_x_squared = tf.Variable(tf.square(log_x))

# Apply Adam
opt = tf.keras.optimizers.Adam(learning_rate=0.7)
loss = lambda: (3 * x**2 + 2 * log_x_squared**2) 

print('start at', 'x:', x.numpy(), 'log(x)^2:', log_x_squared.numpy())
for step in range(10):
  opt.minimize(loss, [x, log_x_squared]).numpy()
  print('step', step, 'x:', x.numpy(), 'log(x)^2:', log_x_squared.numpy())

start at x: 3.0 log(x)^2: 1.206949
step 0 x: 2.3000002 log(x)^2: 0.5069495
step 1 x: 1.6108086 log(x)^2: -0.12726283
step 2 x: 0.9453439 log(x)^2: -0.57190216
step 3 x: 0.3228413 log(x)^2: -0.7434349
step 4 x: -0.23097372 log(x)^2: -0.6961493
step 5 x: -0.68760407 log(x)^2: -0.51386964
step 6 x: -1.024248 log(x)^2: -0.26151392
step 7 x: -1.2320495 log(x)^2: 0.007850885
step 8 x: -1.3173534 log(x)^2: 0.24551828
step 9 x: -1.2964466 log(x)^2: 0.41104752


In [ ]:
# Metrics
import tensorflow as tf
import numpy as np

x = tf.Variable([1,1,0,1,0], tf.int32)
y = tf.Variable([0,1,0,0,1], tf.int32)

acc= tf.metrics.binary_accuracy(x, y)

tf.print(acc)

0.4


In [ ]:
import tensorflow as tf
import numpy as np

